name: Our Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.9.0
          cache: npm
      - run: npm ci --legacy-peer-deps
      - run: npm run build
